services:
  api:
    image: ckalia/linkextractor-api
    build: ./api
    ports:
      - 5000:5000
    volumes:
      - ./api/main.py:/app/main.py
  web:
    image: ckalia/linkextractor-web
    build: ./web
    ports:
      - 80:80
    environment:
      - API_ENDPOINT=http://api:5000/api/
    volumes:
      - ./web:/var/www/html
