services:
  api:
    image: ckalia/linkextractor-api
    build: ./api
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - 5000:5000
    volumes:
      - ./api/main.py:/app/main.py
  web:
    image: ckalia/linkextractor-web
    build: ./web
    ports:
      - 80:80
    environment:
      - API_ENDPOINT=http://api:5000/api/
    volumes:
      - ./web:/var/www/html
  redis:
    image: redis
